diagnostics: Include <atomic> for std::atomic
IWYU. This also fixes the libstdc++ build after commit 6056c0dc4a ("Make
adding crash keys thread safe"):

../../v8/src/diagnostics/crash-key.cc:36:15: error: no template named 'atomic' in namespace 'std'
  static std::atomic<int> last{-1};
         ~~~~~^

Bug: chromium:957519
Change-Id: Ib1f465dc5e4f0b4a212486a9a3bebe54bb6654b3
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/1681129
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Commit-Queue: Jakob Kummerow <jkummerow@chromium.org>
Reviewed-by: Jakob Kummerow <jkummerow@chromium.org>
Cr-Commit-Position: refs/heads/master@{#62446}