MIPS: Fix `This CL enables precise source positions for all V8 compilers`
Fix c3a6ca68d0646b10885ef7017557eaf463db2e4a

Fix compilation failure on MIPS and GCC cross compile that started to appear
after the CL c3a6ca68d0646b10885ef7017557eaf463db2e4a landed. The compilation
error is due to:

.././src/objects-inl.h:4129:54: error: assuming signed overflow does not occur
when assuming that (X + c) < X is always false [-Werror=strict-overflow]
   DCHECK(index >= 0 && length >= 0 && index + length >= index &&

BUG=

Review-Url: https://codereview.chromium.org/2501963002
Cr-Commit-Position: refs/heads/master@{#41067}