[TurboFan] Avoid Gcc compilation fail by Initializing rest_index variable.
  The CL #38858 (https://codereview.chromium.org/2269293004) removed the parameter assignment code
  in rest_parameter(int* index) function in Class DeclarationScope.

  This caused the Gcc compilation fail at the following code in src/compiler/ast-graph-builder.cc, line 576.
  int rest_index;
  Variable* rest_parameter = scope->rest_parameter(&rest_index);
  BuildRestArgumentsArray(rest_parameter, rest_index);

  The error message was:
  ../src/compiler/ast-graph-builder.cc: In member function ‘void v8::internal::compiler::AstGraphBuilder::CreateGraphBody(bool)’:
  ../src/compiler/ast-graph-builder.cc:578:54: error: ‘rest_index’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  BuildRestArgumentsArray(rest_parameter, rest_index);
                                                      ^

  This CL fixed this issue by intializing rest_index to 0.

BUG=

Review-Url: https://codereview.chromium.org/2270363003
Cr-Commit-Position: refs/heads/master@{#38863}