[wasm][decoder] Merge more logic into {PushControl}
Every {PushControl} is surrounded by a {PeekArgs}, {SetBlockType},
{DropArgs}, and {PushMergeValues}.

This CL merges all that into the {PushControl} method, with one
exception: For loops we still need to push the merge values after
invoking the backend, so we have the proper Phi nodes on the value stack
when decoding the loop body.

For other block types, this has the advantage that we do not need to
drop the inputs and push back the merge values, but we instead just
update the type of the existing stack values and are done.

R=jkummerow@chromium.org

Bug: v8:13976
Change-Id: I1006f393f031fceda9e51eb4394de2f584cb71ee
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4521030
Commit-Queue: Clemens Backes <clemensb@chromium.org>
Reviewed-by: Jakob Kummerow <jkummerow@chromium.org>
Cr-Commit-Position: refs/heads/main@{#87608}