[sparkplug] Include SharedFunctionInfo on all platforms
`SharedFunctionInfo` is defined under the added header and
not having it included causes this compilation error:

variable has incomplete type 'v8::internal::SharedFunctionInfo'

Change-Id: Ieb0e8f89043f91decdc93f8b3e3c5ed29c0043c6
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2989133
Commit-Queue: Toon Verwaest <verwaest@chromium.org>
Reviewed-by: Toon Verwaest <verwaest@chromium.org>
Cr-Commit-Position: refs/heads/master@{#75458}