Explicitly constructing the std::pair
older gcc compilers (tested on PPC gcc 6) may throw
a compilation error if std::pair is not constructed explicitly.

<algorithm> header also needs to be included to avoid the following
error:

error: 'remove_if' is not a member of 'std'


Change-Id: Ia7919185614fee1e2e35f2fb25f5fdf05b90e27f
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2149565
Reviewed-by: Michael Lippautz <mlippautz@chromium.org>
Commit-Queue: Milad Farazmand <miladfar@ca.ibm.com>
Cr-Commit-Position: refs/heads/master@{#67133}